<Project>
  <PropertyGroup>
    <ManagePackageVersionsCentrally>true</ManagePackageVersionsCentrally>
    <CentralPackageTransitivePinningEnabled>true</CentralPackageTransitivePinningEnabled>
    <NoWarn>$(NoWarn);NU1507</NoWarn>
  </PropertyGroup>
  <ItemGroup>
    <PackageVersion Include="Avalonia" Version="11.2.3" />
    <PackageVersion Include="Avalonia.Desktop" Version="11.2.3" />
    <PackageVersion Include="Avalonia.Diagnostics" Version="11.2.3" />
    <PackageVersion Include="Avalonia.ReactiveUI" Version="11.2.3" />
    <PackageVersion Include="Avalonia.Themes.Simple" Version="11.2.3" />
    <PackageVersion Include="coverlet.collector" Version="6.0.2" />
    <PackageVersion Include="FluentAssertions" Version="7.0.0" />
    <PackageVersion Include="Microsoft.AspNetCore.Components.WebView.WindowsForms" Version="9.0.12" />
    <PackageVersion Include="Microsoft.CodeAnalysis.Analyzers" Version="3.11.0" />
    <PackageVersion Include="Microsoft.CodeAnalysis.CSharp" Version="4.12.0" />
    <PackageVersion Include="Microsoft.CodeAnalysis.CSharp.Analyzer.Testing" Version="1.1.2" />
    <PackageVersion Include="Microsoft.CodeAnalysis.CSharp.SourceGenerators.Testing" Version="1.1.2" />
    <PackageVersion Include="Microsoft.CodeAnalysis.CSharp.Workspaces" Version="4.12.0" />
    <PackageVersion Include="Microsoft.NET.Test.Sdk" Version="17.12.0" />
    <PackageVersion Include="Microsoft.Web.LibraryManager.Build" Version="2.1.175" />
    <PackageVersion Include="Moq" Version="4.20.72" />
    <PackageVersion Include="MudBlazor" Version="8.5.1" />
    <PackageVersion Include="Nerdbank.GitVersioning" Version="3.7.115" />
    <PackageVersion Include="NLog.Extensions.Logging" Version="5.4.00" />
    <PackageVersion Include="NLog.Web.AspNetCore" Version="5.4.00" />
    <PackageVersion Include="NUnit" Version="4.3.2" />
    <PackageVersion Include="NUnit.Analyzers" Version="4.7.0" />
    <PackageVersion Include="NUnit3TestAdapter" Version="5.0.0" />
    <PackageVersion Include="OpenTelemetry.Exporter.Prometheus.AspNetCore" Version="1.10.0-beta.1" />
    <PackageVersion Include="OpenTelemetry.Extensions.Hosting" Version="1.11.2" />
    <PackageVersion Include="PolySharp" Version="1.15.0" />
    <PackageVersion Include="ReactiveUI" Version="20.2.45" />
    <PackageVersion Include="ReactiveUI.Blazor" Version="20.2.45" />
    <PackageVersion Include="RichardSzalay.MockHttp" Version="7.0.0" />
    <PackageVersion Include="Sentry.NLog" Version="5.5.0" />
    <PackageVersion Include="StyleCop.Analyzers" Version="1.2.0-beta.556" />
    <PackageVersion Include="System.Formats.Asn1" Version="9.0.3" />
    <PackageVersion Include="TestableIO.System.IO.Abstractions.Analyzers" Version="2022.0.0" />
    <PackageVersion Include="TestableIO.System.IO.Abstractions.TestingHelpers" Version="22.0.13" />
    <PackageVersion Include="TestableIO.System.IO.Abstractions.Wrappers" Version="22.0.13" />
    <PackageVersion Include="Velopack" Version="0.0.1053" />
    <PackageVersion Include="WoWsShipBuilder.DataStructures" Version="6.0.0" />
  </ItemGroup>
</Project>
